spring.application.name=replayme

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

aws.region=us-east-2
aws.bucket-name=replay-me-teste-120622641290-us-east-2-an
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}


#aws.region=${AWS_REGION}
#aws.s3.bucket=${AWS_S3_BUCKET}


